# disable sudo to use container based build
sudo: false

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    - TASK=build CXX=g++-4.8
#    - TASK=lint LINT_LANG=cpp
#    - TASK=doc
#    - TASK=unittest_gtest CXX=g++

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - wget
      - git
      - unzip

before_install:
  - export TRAVIS=make/travis
  - source ${TRAVIS}/travis_setup_env.sh


install:
  - pip install cpplint pylint --user `whoami`
  - make -j4 deps DEPS_PATH=${HOME}/.cache/usr


script: ${TRAVIS}/travis_script.sh


before_cache:
  - ${TRAVIS}/travis_before_cache.sh

cache:
  directories:
    - ${HOME}/.cache/usr


notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
